stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: "4hellboy4/docker_example"

before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME:latest .
  only:
    - main

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker run $IMAGE_NAME:latest python -c "print('Test passed!')"
  only:
    - main

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker tag $IMAGE_NAME:latest $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:latest
  only:
    - main
